FROM jelastic/maven:3.9.5-openjdk-21  AS build
WORKDIR /
COPY src src
COPY pom.xml pom.xml

RUN mvn clean install -Dmaven.test.skip=true

FROM eclipse-temurin:21-jdk
#LABEL "com.boa.customerapidocker"="customer-api"
LABEL version=1.0-SNAPSHOT
COPY --from=build target/jaegerdemo-0.0.1-SNAPSHOT.jar jaegerdemo-0.0.1-SNAPSHOT.jar
# Copy Elastic APM agent JAR from build stage
COPY --from=build target/elastic-apm-agent-1.54.0.jar elastic-apm-agent-1.54.0.jar
COPY ca.crt ca.crt

RUN keytool -importcert -noprompt -alias elastic-stack-ca -file ca.crt -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit

EXPOSE 7080
#ENTRYPOINT ["java","-jar","customerapi-0.0.1-SNAPSHOT.jar"]
ENTRYPOINT java   -Delastic.apm.central_config=false -Delastic.apm.service_name=jaegerdemo-observability-demo -Delastic.apm.server_urls=http://host.docker.internal:8200 -Delastic.apm.environment=production -Delastic.apm.secret_token= -Delastic.apm.application_packages=com.cognizant.jaegerdemo -jar jaegerdemo-0.0.1-SNAPSHOT.jar