apm-server:
  host: "0.0.0.0:8200"

  data_streams:
    enabled: true

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "changeme"
  ssl:
    enabled: true
    certificate_authorities: ["/usr/share/ca.crt"]

kibana:
  enabled: true
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"
